stages:
  - terraform-init-plan
  - terraform-apply
  - terraform-output

before_script:
  - cp $AWS_CREDENTIALS ${CI_PROJECT_DIR}/.aws

default:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  cache:
    key: terraform
    paths:
      - ${TF_ROOT}/.terraform


T-Init-plan-EKS-VPC:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform-init-plan
  environment:
    name: production
  script:
    - cd ${TF_ROOT}
    - cp $VAR_FILE variables.tf
    - gitlab-terraform init
    - gitlab-terraform validate
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    expire_in: 3 week
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

T-Apply-EKS-VPC:
  stage: terraform-apply
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  extends:
    - .merge_requst_common
  environment:
    name: production
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform apply
  dependencies:
    - T-Init-plan-EKS-VPC
  needs:
    - T-Init-plan-EKS-VPC
  when: manual
