---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: flux-v2
    commit:
      author:
        email: email
        name: Levon Ananyan
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: flux-v2
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./fluxv2/releases/app/application
    strategy: Setters
